### ISSUE TITLE
NatSpec statistics

### ISSUE THREAD

**Issue by eMarchenko** [komputing/etherscan_contract_downloader#1]
Hi! 
not an issue, just a question: could you share collected statistics about NatSpec usage?

**Comment by ligi** [comment]
sorry - but I do not really have the bandwidth for this currently - chronically out of time. Also I think it would be better to do this on top of sourcify data now. Maybe just do it on your own or find someone with spare time. If you did let me know - I would also be interested in the stats.

**Comment by ligi** [comment]
hm or wait - I think I did some stats real long ago - just need to find the code again - maybe I can just run it again on the current data - but not sure where I put it.
